### ISSUE TITLE
Support for CSS Modules

### ISSUE THREAD

**Issue by tquetano-r7** [hyungjs/csslint-loader#5]
I don't see any documentation for this, but I continue to get an error on an unknown property "composes", which is a property used in CSS Modules (part of the standard css-loader for Webpack). Is there a property I can pass in which accounts for this? For example:

```
csslint?failOnWarning=false&modules=true
```

Or at bare minimum, and easy way to add a custom rule to ignore the composes property?

**Comment by tracker-common** [comment]
This would be awesome.

**Comment by hyungjs** [comment]
@tquetano-r7
Sorry just saw this, for some reason, I wasn't watching this repo.

I'm not getting any error when I used css modules. Could you share parts of your webpack config to see if I can replicate the error?

**Comment by snowman-repos** [comment]
Here's my webpack config. I'm using css modulers but no matter where/how I include csslint it throws errors (resulting from trying to lint JS). Any ideas? Thanks
```
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var OptimizeCssAssetsPlugin = require("optimize-css-assets-webpack-plugin");
var PROD = (process.env.NODE_ENV === "production");
var webpack = require("webpack");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: "build",
    filename: PROD ? "index.min.js" : "index.js"
  },
  module: {
    preLoaders: [
      {
        test: /\.js$/,
        exclude: [/node_modules/, /\.test\.js$/],
        loader: "jshint"
      }
    ],
    loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("css?modules&camelCase=dashes&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]")
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "babel",
        include: __dirname + "/src",
        query: {
          presets: ['es2015']
        }
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("index.min.css"),
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.min\.css$/g,
      cssProcessor: require("cssnano"),
      cssProcessorOptions: {
        discardComments: {
          removeAll: true
        }
      },
      canPrint: true
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  ]
}
```

**Comment by hyungjs** [comment]
@darryl-snow it seems like you're not loading the csslint as part of the loader.

Ex. 
```
{
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract('style', 'css!postcss?pack=defaults!csslint')
}
```

On a separate note, if you don't have legacy code reasons, I'd recommend using sass or less, and using their respective loaders.
